### ISSUE TITLE
Swap does nothing

### ISSUE THREAD

**Issue by asuhler** [Varrenhunter/ProjectOne#1]
Swap, as written, does not actually swap the referenced values. The values swapped in the method are local only variables, and A[i] and A[r] are not global values, so they do not swap. This means that the algorithm never swaps the values.

**Comment by asuhler** [comment]
I have a fix for the issue, if you would like to add me to the project, so I can create another branch and merge it.

**Comment by Varrenhunter** [comment]
Sure! Sorry, I had a test last night, I was concentrating on that.

-Ethan F.
